<?php

return [
    'services' => [
        'appreciation-services' => [
            'label' => 'Appreciation Services',
            'description' => 'Employee & customer appreciation, gifts, recognition programs, and more.',
            'image' => 'perfect-gifts/01.png',
            'options' => [
                'Employee Appreciation',
                'Customer Appreciation',
                'Birthday Recognition',
                'Work Anniversary Recognition',
                'Business Anniversary Recognition',
                'Holiday Appreciation',
                'Thank You Gifts',
                'Congratulations Gifts',
                'Sympathy Gifts',
                'Get Well Gifts',
                'Retirement Recognition',
                'New Hire Welcome Gifts',
                'Handwritten Greeting Cards',
                'Personalized Greeting Cards',
                'Flowers',
                'Cakes',
                'Cookies',
                'Chocolates',
                'Fruit Bouquets',
                'Gift Baskets',
                'Personalized Gifts',
                'Promotional Gifts',
                'Custom Gift Programs',
            ],
        ],
        'marketing-digital-growth' => [
            'label' => 'Marketing & Digital Growth',
            'description' => 'Strategy, social media, content, SEO, websites, and digital growth solutions.',
            'image' => 'e-card/03.jpeg',
            'options' => [
                'Marketing Strategy',
                'Marketing Consulting',
                'Social Media Management',
                'Content Creation',
                'Graphic Design',
                'Video Creation & Editing',
                'Facebook Management',
                'Instagram Management',
                'LinkedIn Management',
                'TikTok Management',
                'X (Twitter) Management',
                'Pinterest Management',
                'YouTube Management',
                'Google Business Profile Management',
                'Email Marketing',
                'Website Design',
                'Website Development',
                'Website Maintenance',
                'Landing Page Design',
                'Search Engine Optimization (SEO)',
                'Reputation Management',
                'CRM Support',
                'AI Business Solutions',
            ],
        ],
        'business-services' => [
            'label' => 'Business Services',
            'description' => 'Printing, branding, HR, consulting, integrations, and business support.',
            'image' => 'greeting_card/business_card.jpg',
            'options' => [
                'Printing',
                'Business Cards',
                'Brochures',
                'Postcards',
                'Promotional Products',
                'Corporate Branding',
                'Employee Recognition Programs',
                'Customer Retention Programs',
                'Travel Services',
                'HR Solutions',
                'Payroll Solutions',
                'Business Consulting',
                'CRM Integrations',
                'API Integrations',
            ],
        ],
        'other' => [
            'label' => 'Other',
            'description' => 'Tell us about any other services your business needs.',
            'image' => 'blogs/1.webp',
            'options' => [
                'Other Services',
            ],
            'has_text_field' => true,
        ],
    ],
];
