<?php

return [
    'tagline' => 'Payroll • HR • Employee Benefits • Hiring & Compliance',
    'description' => 'Gusto is an all-in-one platform designed to help businesses hire, pay, manage, and support their employees from one easy-to-use system.',
    'services' => [
        'payroll-services' => [
            'label' => 'Payroll Services',
            'options' => [
                'Full-Service Payroll',
                'Unlimited Payroll Runs',
                'Automatic Payroll Tax Filing',
                'Federal, State & Local Tax Payments',
                'W-2 & 1099 Preparation',
                'Direct Deposit',
                'Contractor Payments',
                'Multi-State Payroll',
                'Payroll Reports',
                'Employee Self-Service Portal',
                'Payroll Automation',
                'New Hire Reporting',
            ],
        ],
        'human-resources' => [
            'label' => 'Human Resources',
            'options' => [
                'Employee Onboarding',
                'Digital Hiring Documents',
                'Offer Letter Templates',
                'Electronic Signatures',
                'Employee Handbook Builder',
                'Performance Management',
                'Employee Records Management',
                'HR Resource Center',
                'Compliance Assistance',
                'Certified HR Support',
                'Labor Law Alerts',
            ],
        ],
        'employee-benefits' => [
            'label' => 'Employee Benefits',
            'options' => [
                'Health Insurance',
                'Dental Insurance',
                'Vision Insurance',
                'Life Insurance',
                'Disability Insurance',
                '401(k) Retirement Plans',
                'Health Savings Accounts (HSA)',
                'Flexible Spending Accounts (FSA)',
                'Workers’ Compensation',
                'Financial Wellness Tools',
            ],
        ],
        'hiring-onboarding' => [
            'label' => 'Hiring & Onboarding',
            'options' => [
                'Job Postings',
                'Applicant Tracking',
                'Offer Letters',
                'Background Check Integrations',
                'New Hire Checklists',
                'Welcome Workflows',
                'Employee Document Collection',
                'Secure Document Storage',
                'Software Integrations',
            ],
        ],
        'time-attendance' => [
            'label' => 'Time & Attendance',
            'options' => [
                'Time Tracking',
                'PTO Tracking',
                'Vacation Management',
                'Holiday Tracking',
                'Employee Scheduling',
                'Overtime Alerts',
                'Project Time Tracking',
                'Time Clock Integrations',
            ],
        ],
        'business-management' => [
            'label' => 'Business Management',
            'options' => [
                'HR Reporting',
                'Workforce Analytics',
                'Employee Insights',
                'Compliance Notifications',
                'Custom Reports',
                'Secure Employee Portal',
                'Mobile Access',
                'Integrations with Popular Business Software',
                'Cloud-Based Platform',
            ],
        ],
    ],
];
