<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class CareerApplication extends Model
{
    use HasFactory;

    protected $fillable = [
        'career_id',
        'employer',
        'position_for_applying',
        'name',
        'city',
        'state',
        'zip',
        'street_or_email_address',
        'home_phone_number',
        'business_phone_number',
        'cell_number',
        'start_work_date',
        'salary_desired',
        'high_school_diploma',
        'hours',
        'shift',
        'shift_status',
        'authorized_work',
        'convicted',
        'essential_function',
        'accommodation',
        'school_1',
        'degree_1',
        'address_1',
        'school_2',
        'degree_2',
        'address_2',
        'other_school',
        'other_degree',
        'other_address',
        'special_skills',
        'name_1',
        'phone_1',
        'relation_1',
        'name_2',
        'phone_2',
        'relation_2',
        'name_3',
        'address_3',
        'phone_3',
        'relation_3',
        'job1_start_date',
        'job1_end_date',
        'company_name_1',
        'supervisor_name1',
        'phone_number1',
        'city_1',
        'state1',
        'zip1',
        'duties1',
        'reason_for_leaving_1',
        'starting_salary1',
        'ending_salary1',
        'contact_present_employer',
        'job2_start_date',
        'job2_end_date',
        'company_name_2',
        'supervisor_name2',
        'phone_number2',
        'city_2',
        'state2',
        'zip2',
        'duties2',
        'reason_for_leaving_2',
        'starting_salary2',
        'ending_salary2',
        'job3_start_date',
        'job3_end_date',
        'company_name_3',
        'supervisor_name3',
        'phone_number3',
        'city_3',
        'state3',
        'zip3',
        'duties3',
        'reason_for_leaving_3',
        'starting_salary3',
        'ending_salary3',
        'job4_start_date',
        'job4_end_date',
        'company_name_4',
        'supervisor_name4',
        'phone_number4',
        'city_4',
        'state4',
        'zip4',
        'duties4',
        'reason_for_leaving_4',
        'starting_salary4',
        'ending_salary4',
    ];
    
    protected $guarded = [];

    public function career()
    {
        return $this->belongsTo(Career::class, 'career_id', 'id');
    }
}
